#!/usr/bin/env node
// Bundle the MV3 extension into dist/ with esbuild (no config, no framework), then zip it
// into dist/crossword-chat.zip — the stable store-uploadable artifact (kebab-cased repo
// name, never version-stamped, per the shared chrome-extension-release standard), so a
// GitHub Release serves the newest build at a permanent URL:
//   …/releases/latest/download/crossword-chat.zip
// --dev additionally matches the local fake page (http://localhost:8787) so the whole
// voice loop can be rehearsed without an NYT subscription (MT-23).

import { build } from 'esbuild';
import { execFileSync } from 'node:child_process';
import { copyFileSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
const SRC = join(ROOT, 'extension/src');
const DIST = join(ROOT, 'dist');
const dev = process.argv.includes('--dev');

rmSync(DIST, { recursive: true, force: true });
mkdirSync(DIST, { recursive: true });

const entries = [
  { in: join(SRC, 'background/service-worker.js'), out: join(DIST, 'background.js') },
  { in: join(SRC, 'content/content-script.js'), out: join(DIST, 'content.js') },
  { in: join(SRC, 'content/main-world.js'), out: join(DIST, 'main-world.js') },
  { in: join(SRC, 'options/options.js'), out: join(DIST, 'options.js') },
];

for (const { in: input, out } of entries) {
  await build({
    entryPoints: [input],
    outfile: out,
    bundle: true,
    format: 'iife',
    target: 'chrome116',
    sourcemap: dev ? 'inline' : false,
    minify: !dev,
  });
}

copyFileSync(join(SRC, 'options/options.html'), join(DIST, 'options.html'));
copyFileSync(join(SRC, 'popup/unsupported.html'), join(DIST, 'unsupported.html'));

mkdirSync(join(DIST, 'icons'), { recursive: true });
for (const px of [16, 32, 48, 128]) {
  // Colored (manifest default + supported tabs) and gray (unsupported tabs,
  // REQ-LIFE-013) variants; both generated by tools/make-store-assets.mjs.
  for (const name of [`icon-${px}.png`, `icon-${px}-gray.png`]) {
    copyFileSync(join(ROOT, 'extension/icons', name), join(DIST, 'icons', name));
  }
}

const manifest = JSON.parse(readFileSync(join(ROOT, 'extension/manifest.json'), 'utf8'));
if (dev) {
  const devMatch = 'http://localhost:8787/*';
  for (const cs of manifest.content_scripts) cs.matches.push(devMatch);
  manifest.host_permissions.push(devMatch);
  manifest.name += ' (dev)';
}
writeFileSync(join(DIST, 'manifest.json'), JSON.stringify(manifest, null, 2));

// Zip the bundle (manifest at the zip root — store-uploadable). The entries are enumerated
// before the archive is created, so the zip never lists itself; -X drops extra file
// attributes for a tidy, byte-stable archive.
const ZIP_NAME = 'crossword-chat.zip';
execFileSync('zip', ['-rXq', ZIP_NAME, ...readdirSync(DIST)], { cwd: DIST });

console.log(`Built ${dev ? 'dev' : 'production'} bundle → dist/ (+ ${ZIP_NAME})  (load dist/ via chrome://extensions → Load unpacked)`);
